# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Personal info
name: Akshit Grover
title: Docker Community Leader
titles:
- DevOps Practitioner
- Backend Developer
- Computer Science Senior
- Docker Community Leader
email: contact@akshitgrover.dev
phone:
blog: blog.akshitgrover.dev

# Social links
twitter_username: akshitgrover_
github_username:  akshitgrover
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: akshit-grover
xing_username: 
pinterest_username: 
youtube_username: 
googleplus_username:
medium_username: "@akshitgrover_"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Akshit Grover. I am in my <mark>senior year</mark> of <mark>Computer Science</mark> at Vellore Institue of Technology, Vellore, India.
  I take pleasure in creating and building things. I make sure to spend my free time meditating. It is beneficial for maintaing a positive, radical and insightful mental attitude.
  I play guitar to stay positive and creative whenever under stress.
  
  I have been part of many student communities, All those teachings which I got from my seniors helped me take up and justify the responsibilities of <mark>Vice President Technical</mark> at ACM VIT Student Chapter and <mark>Docker Community Leader</mark>.

  Reading books is one exercise I like doing in my free time. It helps me to develop better focus and remain insightful.
  <br>My personal favorite topics are:
  - Lifestyle
  - Spirituality
  - Leadership 
  - Memoirs
  - Biographies  

  I consider myself a slave to humanity and whenever given an opportunity, I do my best to justify the role. I belive in the idea of <mark>Human for Human</mark>. The Sole purpose of our existence is to help others exist; Evolve and innovate collectively for the betterment of the future of existence. 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Let's collaborate #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love working on team projects.<br>
  I am part time open source contributor and have a few contributions in [docker/compose](http://github.com/docker/compose) and [collabnix/dockerlabs](http://github.com/collabnix/dockerlabs).

  If you are working on a project and need a helping hand I would be happy to help.<br>
  Drop me an email [contact@akshitgrover.dev](mailto:contact@akshitgrover.dev)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
